config/routes.rb
Rails.application.routes.draw do

  resources :invitations, only: [:create, :destroy]

	get '/' => 'tops#top'

 	devise_for :users

 	resources :users, only: [:show, :edit, :update]
 	get '/users/:id/follow' => 'users#follow'
 	get '/users/:id/belong' => 'users#belong'

 	resources :teams, only: [:new, :create, :show]
 	get '/teams/:id/member/new' => 'teams#member_new'
 	post '/teams/:id/member/create' => 'teams#member_create'
	get '/teams/:id/member' => 'teams#member'
	post '/teams/:id/member/:id/invite' => 'teams#invite'
  get '/teams/:id/show_add_post' => 'teams#show_add_post'

 	resources :posts, only: [:new, :create]

 	resources :post_favorites, only: [:create, :destroy]

 	resources :follows, only: [:create, :destroy]

 	resources :post_comments, only: [:create]

 	resources :user_points, only: [:create]

 	resources :chats, only: [:show, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
	belongs_to :team
	belongs_to :user

	has_many :notes, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/follow.rb
class Follow < ApplicationRecord
	belongs_to :team
	belongs_to :user
end

app/models/indivisual.rb
class Indivisual < ApplicationRecord
	belongs_to :user
	belongs_to :team
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/member.rb
class Member < ApplicationRecord
	belongs_to :user
	belongs_to :team
end

app/models/note.rb
class Note < ApplicationRecord
	belongs_to :chat
	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :post_favorite_middles, dependent: :destroy

	belongs_to :user
	belongs_to :team

	has_many :post_comments, dependent: :destroy

	attachment :post_image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :post
end

app/models/post_favorite.rb
class PostFavorite < ApplicationRecord

end

app/models/team.rb
class Team < ApplicationRecord
	has_many :members, dependent: :destroy
	has_many :users, through: :members

	has_many :follows, dependent: :destroy
	has_many :users, through: :follows

	has_many :posts, dependent: :destroy

	has_many :chats, dependent: :destroy

	attachment :team_image

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	attachment :image

	has_many :members, dependent: :destroy
	has_many :teams, through: :members

	has_many :follows, dependent: :destroy
	has_many :teams, through: :follows


	has_many :posts, dependent: :destroy

	has_many :user_points, dependent: :destroy

	has_many :notes, dependent: :destroy

end

app/models/user_point.rb
class UserPoint < ApplicationRecord
	belongs_to :user
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def edit
		@user = User.find(current_user.id)
	end

	def update
		@user = User.find(params[:id])

		if @user.update(user_params)
			flash[:notice] = "変更の保存を完了しました"
			redirect_to edit_user_path(@user.id
				)
		else
			flash[:notice] = "変更の保存を失敗しました"
			render 'users/edit'
		end
	end

	def show
		@user = User.find(params[:id])
		@post_comment = PostComment.new
	end

	def follow
		@user = User.find(params[:id])
	end

	def belong
		@user = User.find(params[:id])
	end


	private
	def user_params
		params.require(:user).permit(:image, :name, :email)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/belong.html.erb
<!-- ユーザーマイページ左側の箱 -->
<div class="users_mypage_box">


	<% if @user.id == current_user.id %>
	<div class="users_mypage_left_box_edit_page">
		<%= link_to edit_user_path(@user.id), class:"no-barba" do %>
			<i class="fas fa-ellipsis-h"></i>
		<% end %>
	</div>
	<% end %>

	<!-- ユーザーマイページ上側の部分 -->
	<div class="users_mypage_left_box_image_position">

		<%= attachment_image_tag @user, :image, :fill, 100, 100, fallback: "/images/no_image.jpg", class: "users_mypage_left_box_image" %>

		<div class="users_mypage_left_box_name">
			<%= @user.name %>
		</div>

	</div>
	<!-- ユーザーマイページ上側の部分fin -->


	<!-- ユーザーマイページのフォロー、所属の位置 -->
	<div class="users_show_follow_belong_position">

		<%= link_to user_path(@user.id), class:"users_show_follow_belong_link" do %>
			<div class="user_show_count_under_line">
				<span class="user_show_follow_belong_count"><%= @user.posts.count %></span><span> post</span>
			</div>
		<% end %>

		<%= link_to "/users/#{@user.id}/follow", class:"users_show_follow_belong_link" do %>
			<div class="user_show_count_under_line">
				<span class="user_show_follow_belong_count"><%= @user.follows.count %></span><span> follow</span>
			</div>
		<% end %>

		<%= link_to "/users/#{@user.id}/belong", class:"users_show_follow_belong_link" do %>
			<div class="user_show_count_under_line select_action_under_line">
				<span class="user_show_follow_belong_count"><%= "#{@user.members.count}" %></span><span> belong</span>
			</div>
		<% end %>

	</div>
	<!-- ユーザーマイページのフォロー、所属の位置fin -->




	<!-- pjaxでの切り替えられる箱 -->
	<main id="barba-wrapper">
	<div class="barba-container">
		<div class="users_show_main_content_box">

			<!-- マイページのユーザー所属チーム一覧のflex -->
			<div class="user_show_main_content_box_teams_position">

				<% @user.members.each do |member| %>

					<%= link_to team_path(member.team.id), class:"user_show_main_content_box_link no-barba" do %>
					<div class="user_show_main_content_box_team_box">
						<%= attachment_image_tag member.team, :team_image, :fill, 150, 150, fallback: "/images/no_image.jpg", class: "user_show_main_box_team_box_image" %>
						<p><%= member.team.team_name %></p>
					</div>
					<% end %>
					<!-- link_to のend -->

				<% end %>
				<!-- @user.members.eachのend -->

			</div>

		</div>
	</main>
	</div>
	<!-- pjaxでの切り替えられる箱fin -->



</div>
<!-- ユーザーマイページ左側の箱fin -->


<script>
	$(document).ready(function(){

		Barba.Pjax.start();

		var FadeTransition = Barba.BaseTransition.extend({
	 		start: function() {

		    Promise
	    	 .all([this.newContainerLoading, this.fadeOut()])
	     	 .then(this.fadeIn.bind(this));
	  		},

		fadeOut: function() {
	    	return $(this.oldContainer).animate({ opacity: 0 }).promise();
	  	},

		fadeIn: function() {

	    	var _this = this;
	    	var $el = $(this.newContainer);

		    $(this.oldContainer).hide();

			$el.css({
		  		visibility : 'visible',
		  		opacity : 0
			});

		    $el.animate({ opacity: 1 }, 400, function() {
		      _this.done();
		    });

			  }

			});

		Barba.Pjax.getTransition = function() {
	  		return FadeTransition;
		};

		$('.user_show_count_under_line').click(function(){
			$('.user_show_count_under_line').removeClass('select_action_under_line');
			$(this).addClass('select_action_under_line');
		});

	});
</script>

app/views/users/edit.html.erb
<!-- ユーザーマイページ編集全体の箱 -->
<div class="users_mypage_edit_box clearfix">

	<!-- ユーザーマイページ編集の左側の箱 -->
	<div class="users_mypage_edit_left_box">

		<div class="users_mypage_edit_left_box_content1 users_mypage_edit_left_box_btn users_mypage_edit_left_box_active">
			プロフィールを変更
		</div>

		<div class="users_mypage_edit_left_box_content2 users_mypage_edit_left_box_btn">
			メールアドレスを変更
		</div>


		<div class="users_mypage_edit_left_box_content3 users_mypage_edit_left_box_btn">
			ログアウト
		</div>

		<%= link_to destroy_user_session_path, method: :delete, data: { confirm: 'ログアウトしてよろしいですか？' }, class:"link" do %>
		<% end %>

	</div>




	<%= form_for(@user, url: user_path(id: current_user.id), html: {method: 'patch'}) do |f| %>

		<!-- ユーザーマイページ編集の右側の箱1(プロフィールを編集するページ) -->
		<div class="users_mypage_edit_right_box users_mypage_edit_active">

			<!-- 画像のプレビュー表示と画像を選ぶボタン -->
			<div class="users_mypage_edit_right_row1">
				<div class="users_mypage_edit_right_image">
					<%= attachment_image_tag @user, :image, :fill, 200, 200, fallback: "/images/no_image.jpg", class: "users_mypage_edit_right_image2", id:"users_mypage_edit_preview" %>
				</div>

				<div class="users_mypage_edit_right_upload">
					<%= f.attachment_field :image, id:"users_mypage_edit_img" %>
				</div>
			</div>
			<!-- 画像のプレビュー表示と画像を選ぶボタンfin -->

			<!-- 名前の入力欄 -->
			<div class="users_mypage_edit_right_row2">

				<div class="users_mypage_edit_name">
					名前
				</div>
				<div class="users_mypage_edit_name_form">
					<%= f.text_field :name, class: "users_mypage_edit_right_row2_name" %>
				</div>

			</div>
			<!-- 名前の入力欄fin -->

			<!-- プロフィールの変更の保存ボタン -->
			<div class="user_mypage_edit_right_box_save_btn_potition">
				<%= f.submit 'プロフィールの変更を保存する', class: "user_mypage_edit_right_box_save_btn" %>
			</div>
			<!-- プロフィールの変更の保存ボタンfin -->

		</div>
		<!-- ユーザーマイページ編集の右側の箱(プロフィールを編集するページ)fin -->



		<!-- ユーザーマイページ編集の右側の箱2(メールアドレスを変更するページ) -->
		<div class="users_mypage_edit_right_box">

			<!-- メールアドレスの入力欄 -->
			<div class="users_mypage_edit_right_box2_row">
				<div class="users_mypage_add_form_position">

						<div><%= f.text_field :email, class: "users_mypage_edit_right_row2_name" %></div>

				</div>
			</div>
			<!-- メールアドレスの入力欄fin -->


			<!-- メールアドレスの変更の保存ボタン -->
			<div class="user_mypage_edit_right_box_save_btn_potition">
				<%= f.submit 'メールアドレスの変更を保存する', class: "user_mypage_edit_right_box_save_btn" %>
			</div>
			<!-- メールアドレスの変更の保存ボタンfin -->

		</div>
		<!-- ユーザーマイページ編集の右側の箱(メールアドレスを変更するページ)fin -->

	<% end %>




		<!-- ユーザーマイページ編集の右側の箱3(ログアウトのページ) -->
		<div class="users_mypage_edit_right_box">

			<%= link_to destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしてよろしいですか？"}, class:"user_mypage_edit_sign_out_btn_link" do %>
				<div class="user_mypage_edit_sign_out_btn">
					ログアウト
				</div>
			<% end %>

		</div>
		<!-- ユーザーマイページ編集の右側の箱3(ログアウトのページ)fin -->






</div>
<!-- ユーザーマイページ編集全体の箱fin -->







<script>
$(document).ready(function() {

	//プレビューを表示させる
	 $("#users_mypage_edit_img").change(function(){

	 if (this.files && this.files[0]) {
		 var reader = new FileReader();
		 reader.onload = function (e) {
		   $('#users_mypage_edit_preview').attr('src', e.target.result);
		}
			reader.readAsDataURL(this.files[0]);
		  }
		});

	 // 選択ボタンでマウスを置いたときの処理
	 $('.users_mypage_edit_left_box_btn').hover(
	 	function(){
	 		$(this).css('background-color', '#E5E5E5')
	 		$(this).css('cursor', 'pointer')
	 		$(this).css('cursor', 'hand')
	 	},
	 	function(){
	 		$(this).css('background-color', 'white')
	 	}
	 	);


	 // 選択ボタンを押したときの処理
	 $('.users_mypage_edit_left_box_btn').click(function(){
	 	$('.users_mypage_edit_left_box_active').removeClass('users_mypage_edit_left_box_active');
	 	$(this).addClass('users_mypage_edit_left_box_active');

	 	var number = $('.users_mypage_edit_left_box_btn').index($(this));
	 	$('.users_mypage_edit_active').removeClass('users_mypage_edit_active');
	 	$('.users_mypage_edit_right_box').eq(number).addClass('users_mypage_edit_active');
	 });


});
</script>

app/views/users/follow.html.erb
<!-- ユーザーマイページ左側の箱 -->
<div class="users_mypage_box">

	<% if @user.id == current_user.id %>
	<div class="users_mypage_left_box_edit_page">
		<%= link_to edit_user_path(@user.id), class:"no-barba" do %>
			<i class="fas fa-ellipsis-h"></i>
		<% end %>
	</div>
	<% end %>

	<!-- ユーザーマイページ上側の部分 -->
	<div class="users_mypage_left_box_image_position">

		<%= attachment_image_tag @user, :image, :fill, 100, 100, fallback: "/images/no_image.jpg", class: "users_mypage_left_box_image" %>

		<div class="users_mypage_left_box_name">
			<%= @user.name %>
		</div>

	</div>
	<!-- ユーザーマイページ上側の部分fin -->


	<!-- ユーザーマイページのフォロー、所属の位置 -->
	<div class="users_show_follow_belong_position">

		<%= link_to user_path(@user.id), class:"users_show_follow_belong_link" do %>
			<div class="user_show_count_under_line">
				<span class="user_show_follow_belong_count"><%= @user.posts.count %></span><span> post</span>
			</div>
		<% end %>

		<%= link_to "/users/#{@user.id}/follow", class:"users_show_follow_belong_link" do %>
			<div class="user_show_count_under_line select_action_under_line">
				<span class="user_show_follow_belong_count"><%= @user.follows.count %></span><span> follow</span>
			</div>
		<% end %>

		<%= link_to "/users/#{@user.id}/belong", class:"users_show_follow_belong_link" do %>
			<div class="user_show_count_under_line">
				<span class="user_show_follow_belong_count"><%= "#{@user.members.count}" %></span><span> belong</span>
			</div>
		<% end %>

	</div>
	<!-- ユーザーマイページのフォロー、所属の位置fin -->




	<!-- pjaxでの切り替えられる箱 -->
	<main id="barba-wrapper">
	<div class="barba-container">
		<div class="users_show_main_content_box">

			<!-- マイページのユーザー所属チーム一覧のflex -->
			<div class="user_show_main_content_box_teams_position">

				<% @user.follows.each do |follow| %>

					<%= link_to team_path(follow.team.id), class:"user_show_main_content_box_link no-barba" do %>
					<div class="user_show_main_content_box_team_box">
						<%= attachment_image_tag follow.team, :team_image, :fill, 150, 150, fallback: "/images/no_image.jpg", class: "user_show_main_box_team_box_image" %>
						<p><%= follow.team.team_name %></p>
					</div>
					<% end %>
					<!-- link_to のend -->

				<% end %>
				<!-- @user.members.eachのend -->

			</div>
			<!-- マイページのユーザー所属チーム一覧のflex end -->


		</div>
	</main>
	</div>
	<!-- pjaxでの切り替えられる箱fin -->



</div>
<!-- ユーザーマイページ左側の箱fin -->


<script>
	$(document).ready(function(){



		Barba.Pjax.start();

		var FadeTransition = Barba.BaseTransition.extend({
	 		start: function() {

		    Promise
	    	 .all([this.newContainerLoading, this.fadeOut()])
	     	 .then(this.fadeIn.bind(this));
	  		},

		fadeOut: function() {
	    	return $(this.oldContainer).animate({ opacity: 0 }).promise();
	  	},

		fadeIn: function() {

	    	var _this = this;
	    	var $el = $(this.newContainer);

		    $(this.oldContainer).hide();

			$el.css({
		  		visibility : 'visible',
		  		opacity : 0
			});

		    $el.animate({ opacity: 1 }, 400, function() {
		      _this.done();
		    });

			  }

			});

		Barba.Pjax.getTransition = function() {
	  		return FadeTransition;
		};


		$('.user_show_count_under_line').click(function(){
			$('.user_show_count_under_line').removeClass('select_action_under_line');
			$(this).addClass('select_action_under_line');
		});

	});
</script>

app/views/users/mypage_edit.html.erb
<!-- ユーザーマイページ編集全体の箱 -->
<div class="users_mypage_edit_box clearfix">

	<!-- ユーザーマイページ編集の左側の箱 -->
	<div class="users_mypage_edit_left_box">

		<div class="users_mypage_edit_left_box_content1 users_mypage_edit_left_box_btn users_mypage_edit_left_box_active">
			プロフィールを変更
		</div>

		<div class="users_mypage_edit_left_box_content2 users_mypage_edit_left_box_btn">
			メールアドレスを変更
		</div>

	</div>



	<%= form_for(@user, url: user_edit_path(id: current_user.id), html: {method: 'patch'}) do |f| %>

		<!-- ユーザーマイページ編集の右側の箱1(プロフィールを編集するページ) -->
		<div class="users_mypage_edit_right_box users_mypage_edit_active">
			<!-- フラッシュメッセージ -->
			<% if flash[:notice] %>
			<div class="users_mypage_edit_right_box_flash">
				<%= flash[:notice] %>
			</div>
			<% end %>

			<!-- 画像のプレビュー表示と画像を選ぶボタン -->
			<div class="users_mypage_edit_right_row1">
				<div class="users_mypage_edit_right_image">
					<%= attachment_image_tag @user, :image, :fill, 200, 200, fallback: "/images/no_image.jpg", class: "users_mypage_edit_right_image2", id:"users_mypage_edit_preview" %>
				</div>

				<div class="users_mypage_edit_right_upload">
					<%= f.attachment_field :image, id:"users_mypage_edit_img" %>
				</div>
			</div>
			<!-- 画像のプレビュー表示と画像を選ぶボタンfin -->

			<!-- 名前の入力欄 -->
			<div class="users_mypage_edit_right_row2">
				<table>
					<tr>
						<td>名前</td>
						<td><%= f.text_field :name, class: "users_mypage_edit_right_row2_name" %></td>
					</tr>
				</table>
			</div>
			<!-- 名前の入力欄fin -->

			<!-- プロフィールの変更の保存ボタン -->
			<div class="user_mypage_edit_right_box_save_btn_potition">
				<%= f.submit 'プロフィールの変更を保存する', class: "user_mypage_edit_right_box_save_btn" %>
			</div>
			<!-- プロフィールの変更の保存ボタンfin -->

		</div>
		<!-- ユーザーマイページ編集の右側の箱(プロフィールを編集するページ)fin -->





		<!-- ユーザーマイページ編集の右側の箱2(メールアドレスを変更するページ) -->
		<div class="users_mypage_edit_right_box">

			<!-- メールアドレスの入力欄 -->
			<div class="users_mypage_edit_right_box2_row">
				<table>
					<tr>
						<td>メールアドレス</td>
						<td><%= f.text_field :email, class: "users_mypage_edit_right_row2_name" %></td>
					</tr>
				</table>
			</div>
			<!-- メールアドレスの入力欄fin -->


			<!-- メールアドレスの変更の保存ボタン -->
			<div class="user_mypage_edit_right_box_save_btn_potition">
				<%= f.submit 'メールアドレスの変更を保存する', class: "user_mypage_edit_right_box_save_btn" %>
			</div>
			<!-- メールアドレスの変更の保存ボタンfin -->

		</div>
		<!-- ユーザーマイページ編集の右側の箱(メールアドレスを変更するページ)fin -->

	<% end %>

</div>
<!-- ユーザーマイページ編集全体の箱fin -->





<script>
$(document).ready(function() {

	//プレビューを表示させる
	 $("#users_mypage_edit_img").change(function(){

	 if (this.files && this.files[0]) {
		 var reader = new FileReader();
		 reader.onload = function (e) {
		   $('#users_mypage_edit_preview').attr('src', e.target.result);
		}
			reader.readAsDataURL(this.files[0]);
		  }
		});

	 // 選択ボタンでマウスを置いたときの処理
	 $('.users_mypage_edit_left_box_btn').hover(
	 	function(){
	 		$(this).css('background-color', '#E5E5E5')
	 		$(this).css('cursor', 'pointer')
	 		$(this).css('cursor', 'hand')
	 	},
	 	function(){
	 		$(this).css('background-color', 'white')
	 	}
	 	);


	 // 選択ボタンを押したときの処理
	 $('.users_mypage_edit_left_box_btn').click(function(){
	 	$('.users_mypage_edit_left_box_active').removeClass('users_mypage_edit_left_box_active');
	 	$(this).addClass('users_mypage_edit_left_box_active');

	 	var number = $('.users_mypage_edit_left_box_btn').index($(this));
	 	$('.users_mypage_edit_active').removeClass('users_mypage_edit_active');
	 	$('.users_mypage_edit_right_box').eq(number).addClass('users_mypage_edit_active');
	 });


});
</script>

app/views/users/show.html.erb
<!-- ユーザーマイページ左側の箱 -->
<div class="users_mypage_box">

	<% if @user.id == current_user.id %>
	<div class="users_mypage_left_box_edit_page">
		<%= link_to edit_user_path(@user.id), class:"no-barba" do %>
			<i class="fas fa-ellipsis-h"></i>
		<% end %>
	</div>
	<% end %>

	<!-- ユーザーマイページ上側の部分 -->
	<div class="users_mypage_left_box_image_position">

		<%= attachment_image_tag @user, :image, :fill, 100, 100, fallback: "/images/no_image.jpg", class: "users_mypage_left_box_image" %>

		<div class="users_mypage_left_box_name">
			<%= @user.name %>
		</div>

	</div>
	<!-- ユーザーマイページ上側の部分fin -->


	<!-- ユーザーマイページのフォロー、所属の位置 -->
	<div class="users_show_follow_belong_position">

		<%= link_to user_path(@user.id), class:"users_show_follow_belong_link" do %>
			<div class="user_show_count_under_line select_action_under_line">
				<span class="user_show_follow_belong_count"><%= @user.posts.count %></span><span> post</span>
			</div>
		<% end %>

		<%= link_to "/users/#{@user.id}/follow", class:"users_show_follow_belong_link" do %>
			<div class="user_show_count_under_line">
				<span class="user_show_follow_belong_count"><%= @user.follows.count %></span><span> follow</span>
			</div>
		<% end %>

		<%= link_to "/users/#{@user.id}/belong", class:"users_show_follow_belong_link" do %>
			<div class="user_show_count_under_line">
				<span class="user_show_follow_belong_count"><%= "#{@user.members.count}" %></span><span> belong</span>
			</div>
		<% end %>

	</div>
	<!-- ユーザーマイページのフォロー、所属の位置fin -->



	<!-- pjaxでの切り替えられる箱 -->
	<main id="barba-wrapper">
	<div class="barba-container">
		<div class="users_show_main_content_box">

			<% @user.posts.each do |post| %>
			<%= form_for(@post_comment, data: {remote: true}) do |f| %>
				<div class="users_show_main_content_box_post">

				<div class="users_show_responsive_image_position">
					<%= attachment_image_tag post, :post_image, :fill, 500, 500, fallback: "/images/no_image.jpg", class:"user_show_main_content_box_post_image" %>
				</div>

					<!-- いいねとコメントの箱 -->
					<div class="users_main_content_box_post_favorite_coment_box">

						<%= render partial: 'teams/like_position', locals: {post: post} %>

						<label for="teams_show_right_box_post_comment_form_id">
							<i class="far fa-comment user_show_post_comment"></i>
						</label>

					</div>
					<!-- いいねとコメントの箱fin -->

					<!-- マイページのユーザー投稿の文章の内容 -->
					<% if post.post_comments.present? %>
						<div class="users_show_main_content_box_post_content" data-post="<%=post.id%>">
						<%= post.post_content %>
						</div>
					<% else %>
						<div class="users_show_main_content_box_post_content2" data-post="<%=post.id%>">
						<%= post.post_content %>
						</div>
					<% end %>
					<!-- マイページのユーザー投稿の文章の内容fin -->


					<!-- マイページのユーザーコメント1つ1つ -->
					<div class="users_show_main_content_box_post_comment_box">
						<%= render partial: 'teams/comment_position', locals: {post: post} %>
					</div>
					<!-- マイページのユーザーコメント1つ1つfin -->


					<!-- マイページユーザー投稿のコメント投稿 -->
					<div class="users_show_main_content_box_comment_form_position">

						<%= f.text_field :post_comment, placeholder: "コメントを入力...", class:"users_show_main_content_box_post_comment_form", id:"teams_show_right_box_post_comment_form_id" %>


						<%= f.hidden_field :post_id, :value => post.id %>
						<%= button_tag type:"submit", class:"teams_show_right_bix_post_comment_btn" do %>
							<i class="fab fa-telegram-plane users_show_right_main_content_comment_btn_plane"></i>
						<% end %>

					</div>

				</div>
			<% end %>
			<!-- form_forのend -->
			<% end %>
			<!-- @user.posts.eachのend -->


		</div>
	</main>
	</div>
	<!-- pjaxでの切り替えられる箱fin -->



</div>
<!-- ユーザーマイページ左側の箱fin -->


<script>
	$(document).ready(function(){



		Barba.Pjax.start();

		var FadeTransition = Barba.BaseTransition.extend({
	 		start: function() {

		    Promise
	    	 .all([this.newContainerLoading, this.fadeOut()])
	     	 .then(this.fadeIn.bind(this));
	  		},

		fadeOut: function() {
	    	return $(this.oldContainer).animate({ opacity: 0 }).promise();
	  	},

		fadeIn: function() {

	    	var _this = this;
	    	var $el = $(this.newContainer);

		    $(this.oldContainer).hide();

			$el.css({
		  		visibility : 'visible',
		  		opacity : 0
			});

		    $el.animate({ opacity: 1 }, 400, function() {
		      _this.done();
		    });

			  }

			});

		Barba.Pjax.getTransition = function() {
	  		return FadeTransition;
		};

		$('.user_show_count_under_line').click(function(){
			$('.user_show_count_under_line').removeClass('select_action_under_line');
			$(this).addClass('select_action_under_line');
		});

	});
</script>