config/routes.rb
Rails.application.routes.draw do

  resources :invitations, only: [:create, :destroy]

	get '/' => 'tops#top'

 	devise_for :users

 	resources :users, only: [:show, :edit, :update]
 	get '/users/:id/follow' => 'users#follow'
 	get '/users/:id/belong' => 'users#belong'

 	resources :teams, only: [:new, :create, :show]
 	get '/teams/:id/member/new' => 'teams#member_new'
 	post '/teams/:id/member/create' => 'teams#member_create'
	get '/teams/:id/member' => 'teams#member'
	post '/teams/:id/member/:id/invite' => 'teams#invite'
  get '/teams/:id/show_add_post' => 'teams#show_add_post'

 	resources :posts, only: [:new, :create]

 	resources :post_favorites, only: [:create, :destroy]

 	resources :follows, only: [:create, :destroy]

 	resources :post_comments, only: [:create]

 	resources :user_points, only: [:create]

 	resources :chats, only: [:show, :create]

end

app/models/chat.rb
class Chat < ApplicationRecord
	belongs_to :team
	belongs_to :user

	has_many :notes, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/follow.rb
class Follow < ApplicationRecord
	belongs_to :team
	belongs_to :user
end

app/models/indivisual.rb
class Indivisual < ApplicationRecord
	belongs_to :user
	belongs_to :team
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/member.rb
class Member < ApplicationRecord
	belongs_to :user
	belongs_to :team
end

app/models/note.rb
class Note < ApplicationRecord
	belongs_to :chat
	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :post_favorite_middles, dependent: :destroy

	belongs_to :user
	belongs_to :team

	has_many :post_comments, dependent: :destroy

	attachment :post_image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :post
end

app/models/post_favorite.rb
class PostFavorite < ApplicationRecord

end

app/models/team.rb
class Team < ApplicationRecord
	has_many :members, dependent: :destroy
	has_many :users, through: :members

	has_many :follows, dependent: :destroy
	has_many :users, through: :follows

	has_many :posts, dependent: :destroy

	has_many :chats, dependent: :destroy

	attachment :team_image

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	attachment :image

	has_many :members, dependent: :destroy
	has_many :teams, through: :members

	has_many :follows, dependent: :destroy
	has_many :teams, through: :follows


	has_many :posts, dependent: :destroy

	has_many :user_points, dependent: :destroy

	has_many :notes, dependent: :destroy

end

app/models/user_point.rb
class UserPoint < ApplicationRecord
	belongs_to :user
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Squad</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" rel="stylesheet">
    <!-- <script src="javascripts/barba.min.js" type="text/javascript"></script> -->
  </head>

  <body>

  <!-- wrap -->
  <div class="wrap">

    <header>
      <!-- ヘッダーの要素の幅 -->
      <div class="header_wide clearfix">

        <!-- ヘッダー左側要素（タイトル） -->
        <%= link_to "/", class:"header_left_link no-barba" do %>
          <div class="header_left">
            Squad
          </div>
        <% end %>
        <!-- ヘッダー左側要素fin -->

      <% if current_user.present? %>
        <% header_invitations = Invitation.where(user_id: current_user.id) %>
        <% if header_invitations.present? %>

          <div class="header_right_bell_position">
            <i class="fas fa-bell header_right_bell"></i>
            <div class="header_right_balloon header_right_balloon_none">
              <% header_invitations.each do |header_invitation| %>
                <div class="header_right_invite_row header_right_invite_row_<%=header_invitation.team_id%>" >
                  <div class="header_right_team_name">
                    <p><%=  header_invitation.team.team_name %></p>
                    <p>からチームに招待されています</p>
                  </div>

                  <div class="header_right_yes_btn" data-header-row-number="<%=header_invitation.team_id%>">
                    参加
                  </div>

                  <div class="header_right_no_btn" data-header-row-number="<%=header_invitation.team_id%>">
                    拒否
                  </div>
                </div>
              <% end %>
              <!-- header_invitation.eachのend -->
            </div>
          </div>

        <% end %>
        <!-- if header_invitationsのend -->
      <% end %>
      <!-- if current_user.presentのend -->

      </div>
      <!-- ヘッダーの要素の幅fin -->
    </header>


    <div class="contents clearfix">
      <%= yield %>
    </div>


    <footer class="clearfix">

      <!-- フッターの要素の幅と高さ -->
      <div class="footer_wide clearfix">

        <!-- ログインしているとき -->
        <% if user_signed_in? %>
          <!-- ヘッダー右側要素（リンク） -->
          <div class="footer_right clearfix">

            <%= link_to new_team_path, class: "footer_right_link no-barba" do %>
              <div class="footer_right_link_btn">
                <i class="fas fa-handshake footer_right_link_btn_icon"></i>
              </div>
            <% end %>

            <%= link_to "/users/#{current_user.id}/belong", class: "footer_right_link no-barba" do %>
              <div class="footer_right_link_btn">
                <i class="fas fa-users footer_right_link_btn_icon"></i>
              </div>
            <% end %>

            <%= link_to user_path(current_user.id), class: "footer_right_link no-barba" do %>
              <div class="footer_right_link_btn">
                <i class="fas fa-user footer_right_link_btn_icon"></i>
              </div>
            <% end %>
          </div>
            <!-- ヘッダー右側要素fin -->


        <!-- ログインしていないとき -->
        <% else %>
          <!-- ヘッダー右側要素（リンク） -->
          <div class="footer_right clearfix">
            <%= link_to new_user_registration_path, class: "footer_right_link_before no-barba" do %>
              <div class="footer_right_link_btn">
                <i class="fas fa-file-signature"></i>
              </div>
            <% end %>


            <%= link_to new_user_session_path, class: "footer_right_link_before no-barba" do %>
              <div class="footer_right_link_btn">
                <i class="fas fa-door-open"></i>
              </div>
            <% end %>

          </div>


            <!-- ヘッダー右側要素fin -->
        <% end %>

      </div>
      <!-- フッターの要素の幅と高さfin -->

    </footer>

  </div>
  <!-- wrapfin -->

<script>

  $(document).ready(function(){


    $('.header_right_bell_position').click(function(){

      if ( $('.header_right_balloon').hasClass('header_right_balloon_none') ) {
        $('.header_right_balloon').removeClass('header_right_balloon_none');
      } else {
        $('.header_right_balloon').addClass('header_right_balloon_none');
      }

    });


    // 参加ボタンを押したとき
    const index_number = $(this).index();

    $('.header_right_yes_btn').click(function(){
      const number = $(this).data('header-row-number');

      $.ajax({
        url: `/teams/${number}/member/create`,
        type: "post",
        dataType: "script"
      }).done(function(){
        $('.header_right_invite_row:eq(' + index_number +')').fadeOut();
      }).fail(function(){
        alert("通信に失敗しました");
      });
    });


    // 拒否ボタンを押したとき
    // なぜが、コントローラーにはいくが、通信に失敗するので後で改善する。
    const no_index_number = $(this).index();

    $('.header_right_no_btn').click(function(){
      const number = $(this).data('header-row-number');

      $.ajax({
        url: `/invitations/${number}`,
        type: "delete",
        dataType: "script"
      }).done(function(){
        $('.header_right_invite_row:eq(' + no_index_number +')').fadeOut();
      }).fail(function(){
        alert("通信に失敗しました");
      });
    });


  });


</script>


  </body>


</html>

app/views/messages/new.html.erb
<form id="form">
	<input type="submit">
</form>

<script>

	var dispatcher = new WebSocketRails("localhost:3000/WebSocket");
	var form = document.getElementById("form");

	form.onsubmit = function(e){
		disapatcher.trigger("send_message");
		e.preventDefault();
	}

	dispatcher.bind("spread_message", function(data){
		console.log(data.msg);
	});


</script>

app/views/rooms/_message.html.erb
<%= talk.content %>

app/views/rooms/show.html.erb
<h1>chat Rooms</h1>


<form>
	<label>Say somthing:</label><br>
	<input type="text" data-behavior="room_speaker">

</form>